module myportfolio {
    const currentYear = new Date().getUTCFullYear();
    export const config: IConfiguration = {
        list: {
            columns: {
                names: {
                    'isin': 'ISIN',
                    'name': 'Name',
                    'bi-1_Month_Performance': 'BI-Perf 1M',
                    'bi-1_Year_Performance': 'BI-Perf 1Y',
                    'bi-6_Months_Performance': 'BI-Perf 6M',
                    'bi-Area': 'BI-Area',
                    'bi-Ask_Price': 'BI-Ask Price',
                    'bi-Ask_Volume': 'BI-Ask Volume',
                    'bi-Benchmark': 'BI-Benchmark',
                    'bi-Benchmark_Area': 'BI-Benchmark Area',
                    'bi-Bid_Price': 'BI-Bid Price',
                    'bi-Bid_Volume': 'BI-Bid Volume',
                    'bi-Class': 'BI-Class',
                    'bi-contracts_1M': 'BI-Contracts 1M',
                    'bi-contracts_1Y': 'BI-Contracts 1Y',
                    'bi-contracts_3M': 'BI-Contracts 3M',
                    'bi-contracts_6M': 'BI-Contracts 6M',
                    'bi-Currency_Denomination': 'BI-Currency Denomination',
                    'bi-Date_Time_Last_Trade': 'BI-Last Trade Date',
                    'bi-Day_closing_auction_price': 'BI-Day Closing Auction Price',
                    'bi-Day_High': 'BI-Day High',
                    'bi-Day_Low': 'BI-Day low',
                    'bi-Denomination': 'BI-Denomination',
                    'bi-Dividends': 'BI-Dividends',
                    'bi-EMS': 'BI-EMS',
                    'bi-iNAV_Bloomberg_Ticker': 'BI-Bloomberg iNAV',
                    'bi-iNAV_Reuters_Ric': 'BI-Reuters iNAV',
                    'bi-Instrument_Bloomberg_Ticker': 'BI-Bloomberg',
                    'bi-Instrument_Reuters_Ric': 'BI-Reuters',
                    'bi-Instrument_Type': 'BI-Instrument Type',
                    'bi-Issuer': 'BI-Issuer',
                    'bi-Last_Volume': 'BI-Last Volume',
                    'bi-Lot_Size': 'BI-Lot Size',
                    'bi-Market_Status': 'BI-Market Status',
                    'bi-Mid_Price': 'BI-Mid Price',
                    'bi-Multiplier': 'BI-Multiplier',
                    'bi-Net_Chng': 'BI-Net Change',
                    'bi-Number_Trades': 'BI-Trades',
                    'bi-Official_Close': 'BI-Official Close',
                    'bi-Opening': 'BI-Opening',
                    'bi-PercentageChng': 'BI-Change %',
                    'bi-Performance_Year_to_Date': 'BI-Perf YTD',
                    'bi-Protection_Level': 'BI-Protection Level',
                    'bi-Reference_Close': 'BI-Reference Close',
                    'bi-Segment': 'BI-Segment',
                    'bi-Specialist_obligation_Max_spread_': 'BI-Max Spread',
                    'bi-Subscription,_Redemption,_Performance_Fees': 'BI-Redemption Perf Fees',
                    'bi-Total_Annual_Fees': 'BI-Total Annual Fees',
                    'bi-Total_Quantity': 'BI-Total Qty',
                    'bi-Turnover': 'BI-Turnover',
                    'bi-Year_High': 'BI-Year High',
                    'bi-Year_High_Date': 'BI-Year High Date',
                    'bi-Year_Low': 'BI-Year Low',
                    'bi-Year_Low_Date': 'BI-Year Low Date',
                    'calc-dividendYield_2017': 'CALC- Yield 2017',
                    'calc-dividendYield_2018': 'CALC- Yield 2018',
                    'calc-dividendYield_2019': 'CALC- Yield 2019',
                    'calc-dividendYield_rolling': 'CALC- Yield Rolling',
                    'je-assetClass': 'JE-Asset Class',
                    'je-bondType': 'JE-Bond Type',
                    'je-equityStrategy': 'JE-Equity Strategy',
                    'je-sector': 'JE-Equity Sector',
                    'je-country': 'JE-Country',
                    'je-description': 'JE-Description',
                    'je-distributionPolicy': 'JE-Distribution Policy',
                    'je-domicileCountry': 'JE-Domicile Country',
                    'je-weekReturnCUR': 'JE-Return 1W',
                    'je-monthReturnCUR': 'JE-Return 1M',
                    'je-threeMonthReturnCUR': 'JE-Return 3M',
                    'je-sixMonthReturnCUR': 'JE-Return 6M',
                    'je-yearReturnCUR': 'JE-Return 1Y',
                    'je-threeYearReturnCUR': 'JE-Return 3Y',
                    'je-fiveYearReturnCUR': 'JE-Return 5Y',
                    'je-ytdReturnCUR': 'JE-Return YTD',
                    'je-yearReturn1CUR': `JE-Return ${currentYear - 1}`,
                    'je-yearReturn2CUR': `JE-Return ${currentYear - 2}`,
                    'je-yearReturn3CUR': `JE-Return ${currentYear - 3}`,
                    'je-yearReturn4CUR': `JE-Return ${currentYear - 4}`,
                    'je-yearReturnPerRiskCUR': 'JE-Return per Risk 1Y',
                    'je-threeYearReturnPerRiskCUR': 'JE-Return per Risk 3Y',
                    'je-fiveYearReturnPerRiskCUR': 'JE-Return per Risk 5Y',
                    'je-yearVolatilityCUR': 'JE-Volatility 1Y',
                    'je-threeYearVolatilityCUR': 'JE-Volatility 3Y',
                    'je-fiveYearVolatilityCUR': 'JE-Volatility 5Y',
                    'je-fundCurrency': 'JE-Currency',
                    'je-fundSize': 'JE-Size',
                    'je-groupValue': 'JE-Group Value',
                    'je-hasSecuritiesLending': 'JE-Securities Lending',
                    'je-inceptionDate': 'JE-Inception Date',
                    'je-lastQuotation': 'JE-Last Quotation',
                    'je-name': 'JE-Name (JustETF)',
                    'je-replicationMethod': 'JE-Replication Method',
                    'je-savingsPlanReady': 'JE-Savings Plan',
                    'je-ter': 'JE-TER',
                    'je-ticker': 'JE-Ticker',
                    'je-wkn': 'JE-WKN',
                    'ms-MarketCap': 'MS-Market Cap',
                    'ms-IndustryName': 'MS-MS Industry Name',
                    'ms-ClosePrice': 'MS-Close Price',
                    'ms-ReturnD1': 'MS-Return 1D (MS)',
                    'ms-ReturnM0': 'MS-Return 0M (MS)',
                    'ms-ReturnM1': 'MS-Return 1M (MS)',
                    'ms-ReturnM12': 'MS-Retuen 1Y (MS)',
                    'ms-ReturnM120': 'MS-Return 10Y (MS)',
                    'ms-ReturnM3': 'MS-Return 3M (MS)',
                    'ms-ReturnM36': 'MS-Return 3Y (MS)',
                    'ms-ReturnM6': 'MS-Return 6M (MS)',
                    'ms-ReturnM60': 'MS-Return 5Y (MS)',
                    'ms-ReturnW1': 'MS-Return 1W (MS)',
                    'ms-LegalName': 'MS-Legal Name',
                    'ms-Name': 'MS-Name (MS)',
                    'ms-PriceCurrency': 'MS-Currency (MS)',
                    'ms-StarRatingM255': 'MS-MS Rating',
                    'ms-Ticker': 'MS-Ticker',
                    'ms-TrackRecordExtension': 'MS-Track Record Extension',
                    'ms-DividendYield': 'MS-Yield 1Y',
                },
                visibility: ['isin', 'name', 'je-ter', 'je-assetClass', 'ms-CategoryName'],
                typeIsNumber: ['ms-DividendYield'],
                filterable: ['je-assetClass', 'je-bondType', 'je-equityStrategy', 'je-sector', 'je-country', 'ms-CategoryName', 'je-distributionPolicy', 'je-fundCurrency'],
                sortOrder: ['name', 'isin', 'je-description', 'je-ter', 'je-assetClass']
            }
        }
    }
};
